### PR TITLE
feat: added dockerfile/docker-compose

### PR DESCRIPTION
**Pull request by mapleknight**
This PR offers the functionality to use docker-compose to spin up a clean application environment

### CODE REVIEW

**Review by MarkDWilliams — APPROVED** [review]

**Comment by MarkDWilliams** [comment]
@mapleknight I tried pulling this code and starting things up, but ran into some problems.  I pulled down the code and then ran
`docker build -t ars .`
`docker run -dp 8000:8000 ars` 
This seems to run fine, but when I try to send a query to my local host with 
` curl -X POST "http://localhost:8000/ars/api/submit" -H  "accept: application/json" -H  "Content-Type: application/json" -d @snyderGene.json` 
which is how I would typically do it, but I get 
```
raceback (most recent call last):
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such table: tr_ars_channel) was the direct cause of the following exception:
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 66, in submit
    actor=get_default_actor())
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 46, in get_default_actor
    return get_or_create_actor(DEFAULT_ACTOR)[0]
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 319, in get_or_create_actor
    channel, created = Channel.objects.get_or_create(name=channel)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

During handling of the above exception (no such table: tr_ars_channel), another exception occurred:
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 76, in submit
    logger.debug("Unexpected error: %s" % sys.exc_info())
```

Am I making some error in my usage of docker (apologies, I am not a docker expert) or is there another issue causing this?

**Comment by mapleknight** [comment]
@MarkDWilliams To spin up the stack, we only need to run `docker-compose up -d`. The only port exposed by default is arsserver with port 8000. We can modify/add port mapping for each service in the docker-compose file if we want to test each component. 
To rebuild the image after your code change, we will use `docker-compose build --no-cache`. 
To stop the stack, we can use `docker-compose stop`. 
To tear down the stack completely, including images, we will use `docker-compose down --rmi all`. 
For more docker-compose commands, please refer to https://docs.docker.com/compose/reference/.
Another point is that the MySQL database is not persistent in this setup. To persist the MySQL data, refer to https://hub.docker.com/_/mysql in the section of "Where to Store Data".

**Comment by MarkDWilliams** [comment]
@mapleknight I tried this as per your instructions, but I'm still seeing this when I try to query.  Is there something at issue with the database?
```
Traceback (most recent call last):
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such table: tr_ars_channel) was the direct cause of the following exception:
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 66, in submit
    actor=get_default_actor())
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 46, in get_default_actor
    return get_or_create_actor(DEFAULT_ACTOR)[0]
  File "/Users/williamsmard/Software/RelayTest/Relay/tr_sys/tr_ars/api.py", line 319, in get_or_create_actor
    channel, created = Channel.objects.get_or_create(name=channel)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/Users/williamsmard/Software/Relay/env/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
```

**Comment by MarkDWilliams** [comment]
Thank you for your help in walking through this @mapleknight , everything seems to be good.  @southalln I believe we need to make some slight changes to the docker startup to allow for an existing db to be used and we'll need to convert the existing sqlite db in prod to MySQL, but we'll be good to go after that.

**Review by southalln — APPROVED** [review]
Approve now, but should refactor shortly to miminize redundancy with existing setting.py and other ARS code.

**Pull request merged**
