### PR TITLE
Aragorn experimental inclusion

### PR DESCRIPTION
**Pull request by PhillipsOwen**
ARAGORN experimental: Performs a query operation which compiles data from numerous ARAGORN ranking agent services including Strider, Answer coalesce and Aragorn-ranker.

### CODE REVIEW

**Comment by southalln** [comment]
The fixtures edits are not needed --- this should be detritus at this point, BUT, there's no harm. I fugured Mark's eagle eyes would be helpful for other aspects of the template for a new agent. And I didn't see Travis kicked off, either, so I'm wondering about that too.

**Comment by PhillipsOwen** [comment]
ok, thanks for the eyeball. this is my first time attempting this so expect rookie mistakes.

i see that some checks were run (successfully). although it looks like just a "greetings" workflow.

**Comment by MarkDWilliams** [comment]
@PhillipsOwen I corrected a few issues with this in another branch, but am still running into an issue.  When I hit http://aragorn.renci.org/query even directly, I get a 302 Permanently Moved return.  Is this the correct URL?

**Comment by PhillipsOwen** [comment]
http is not supported, please use https.

that said when i try it using https i get "method not allowed" which i will look into now.

**Comment by PhillipsOwen** [comment]
there was an error on my side when the default body is POSTed. i am about to deploy the fix now.

also note, this endpoint will only accept POSTs

**Comment by MarkDWilliams** [comment]
With the change to HTTPS, it seems to be accepting the query and returning a 200 for it, but it is also not returning any results for the status query you provided.  I'm getting `Error detected. Got an empty result from strider, aborting."` when I send that query through the ARS or directly to https://aragorn.renci.org/query.  Can you provide a query that will return results  for me to test with?

**Comment by PhillipsOwen** [comment]
the strider service appears to be down. unfortunately that all you will get until it comes back on line.

I will check with those folks to see about status.

**Comment by PhillipsOwen** [comment]
the strider server was just restarted and now aragorn is outputting results. please try again.

**Comment by MarkDWilliams** [comment]
I just tried it again, but it seems I still got the same 
`Error detected. Got an empty result from strider, aborting.`
message, both through my local instance of the ARS as well as sending directly to the https://aragorn.renci.org/query URL.  Is this URL correct, and is this query correct?
`{
  "message": {
    "query_graph": {
      "nodes": {
        "n00": {
          "id": "MONDO:0005784",
          "category": "biolink:Disease"
        },
        "n01": {
          "category": "biolink:Disease"
        }
      },
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicate":"biolink:subclass_of"
        }
      }
    }
  }
}
`

**Comment by PhillipsOwen** [comment]
it looks like it is down yet again. sorry about this. the strider server is definitely having a bad day.

**Comment by MarkDWilliams** [comment]
Phil, I had a few problems with the code here to register the experimental service but I just did the registration in a different branch/PR, which I have now merged.  So, you should be all good to go https://github.com/NCATSTranslator/Relay/pull/124

**Pull request closed without merging**
